### ISSUE TITLE
Search page - 검색 시 해당 단어를 포함하는 게시물 보여주는 기능

### ISSUE THREAD

**Issue by 2017100898** [2017100898/flutter_everytime_clone#2]
<img width="300" src="https://user-images.githubusercontent.com/64299475/143669525-d5618553-04e4-4f89-a424-d38017798219.png"> <img width="300" src="https://user-images.githubusercontent.com/64299475/143669494-7c35411e-44d0-477a-a808-f00ca316f4d9.png">

`flutter: [0, 1, 3, 4, 6, 7]`

* 특정 문자 검색 시, 해당 문자를 포함하는 게시물만 정리되는 것이 print 를 통해서는 확인할 수 있으나 위젯으로는 확인이 안 되는 문제 발생
* 현재는 stack 과 visibility로 검색해보세요 페이지를 컨트롤하고 있지만 별로 좋은 방법이 아니라 생각해서 수정 필요
* 위 문제가 해결 된 이후에, 유저가 두 가지 단어를 입력했을 때 어떻게 처리할 것인지에 대해서도 고민해 봐야 함 

### Todo List
- [ ] 위젯 생명 주기에 대한 이해
- [ ] async, await, Future 공부
- [ ] search page 재구현
